# Simple deployment used to deploy and manage the app in nigelpoulton/ps-web:1.0
# labels (app: web) labels are pretty important to make the load balance 
# deployment wraps (pods) pods, pods wraps container, container contains 
# 5 replicas means 5 pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 10
  minReadySeconds: 10 # this is the time to wait until the pod is ready - related to rolling update and rollback
  strategy:
    type: RollingUpdate # this is the default strategy related to changes in container image
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: hello-pod
        image: nigelpoulton/getting-started-k8s:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080