apiVersion: v1
kind: Service
metadata:
  name: ps-nodeport
spec:
  type: NodePort # ClusterIP, NodePort, LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31111
    protocol: TCP
  selector:
    app: web
    