# LoadBalancer Service. Will only work on supported cloud platforms (AKS, EKS, GKE, DOK, IBM, LKE etc...)
# Listens externally on 80 and forwards to Pod/container on 8080
# the job service is high-level stable abstraction point for multiple pods. it provide basically load balance 
apiVersion: v1
kind: Service # connect direct to the IP pod is not reliable, that’s why we need services
metadata:
  name: ps-lb
spec:
  type: LoadBalancer # this is the type of service, when we use load balancer, we can use as external IP. No need to use node port
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: web # this is the pod label name; this match the pod name 
