apiVersion: v1
kind: Service
metadata:
  name: ps-nodeport
spec:
  type: NodePort # ClusterIP, NodePort, LoadBalancer
  ports:
  - port: 80 # this is the port that the service is listening inside the cluster
    targetPort: 8080 # this is the port that the pod is listening inside the container
    nodePort: 31111 # this is the port that the service is listening outside the cluster. external port
    protocol: TCP
  selector:
    app: web
    